#!/usr/bin/env python
# -*- coding: utf-8 -*-
#  
#  EasyHybrid: Python interface for QM/MM and molecular simulations using pDynamo3
#  Module: Selection utilities for pDynamo systems
#
#  Copyright 2022-2025 Fernando Bachega
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#  Maintainer:
#      Fernando Bachega <ferbachega@gmail.com> or <easyhybrid3@gmail.com>
#
#  Description:
#      Provides functions for selecting atoms and residues in pDynamo systems
#      to facilitate QM/MM partitioning and molecular simulations.
#
import gi

gi.require_version("Gtk", "3.0")
from gi.repository import Gtk
from gi.repository import Gdk
from gi.repository import GdkPixbuf
import os

import threading
import time

from util.geometric_analysis            import get_distance 
from util.geometric_analysis            import get_dihedral 
from util.geometric_analysis            import get_angle 
#from util.periodic_table import atomic_dic 

from util.sequence_plot import GtkSequenceViewer
from pprint import pprint

import numpy as np

class FolderChooserButton:
    """ Class doc """
    
    def __init__ (self, main = None, sel_type = 'folder', home  = None, parent = None):
        """ Class initialiser """
        self.main     =  main
        self.btn      =  Gtk.Button()
        self.sel_type =  sel_type # file/folder
        
        
        if parent:
            self.parent = parent
        else:
            self.parent =  self.main.window
        
        #self.sel_type = 'file' # file/folder

        grid = Gtk.Grid ()
        grid.set_column_spacing (10)
        img = Gtk.Image()
        img.set_from_file(os.path.join(self.main.home,'src/gui/icons/icon_open.png'))
        self.label = Gtk.Label ('...')
        self.btn.connect('clicked', self.open_filechooser)

        grid.attach (img, 0, 0, 1, 1)
        grid.attach (self.label, 1, 0, 1, 1)
        grid.show_all ()    

        self.btn.add (grid)        
        #return self.btn 
        
        self.folder = None
        if home:
            self.set_folder ( folder = home)
        
        self.set_tooltop('The working directory is where EasyHybrid suggests saving any files generated by the simulation routines. This is a dynamic variable that can be easily changed at any time while using the interface.')
    #====================================================================================
    def set_folder (self, folder = '/home'):
        """ Function doc """
        if folder == None:
            self.folder = os.environ.get('HOME')
        else:
            self.folder = folder
        print( self.folder)
        name = os.path.basename(self.folder )
        #print( name)
        self.label.set_text(name)
        return self.folder
        #self.main.pdynamo_session.systems[self.main.pdynamo_session.active_id]['working_folder'] = self.folder
    #====================================================================================
    def get_folder (self):
        """ Function doc """
        return self.folder
        
    #====================================================================================    
    def open_filechooser (self, parent = None):
        """ Function doc """
        
        if self.sel_type == 'folder':
            dialog = Gtk.FileChooserDialog(
                
                #title="Please choose a file", parent=window, action=Gtk.FileChooserAction.OPEN
                title="Please choose a folder", parent = self.parent, action=Gtk.FileChooserAction.SELECT_FOLDER
            )
            dialog.set_select_multiple(True)
            dialog.add_buttons(
                Gtk.STOCK_CANCEL,
                Gtk.ResponseType.CANCEL,
                Gtk.STOCK_OPEN,
                Gtk.ResponseType.OK,
            )
        
        else:
            dialog = Gtk.FileChooserDialog(
                
                #title="Please choose a file", parent=window, action=Gtk.FileChooserAction.OPEN
                title="Please choose a file", parent= self.parent, action=Gtk.FileChooserAction.OPEN
            )
            dialog.add_buttons(
                Gtk.STOCK_CANCEL,
                Gtk.ResponseType.CANCEL,
                Gtk.STOCK_OPEN,
                Gtk.ResponseType.OK,
            )
        
        
        
        if self.folder:
            dialog.set_current_folder(self.folder)
        else:
            dialog.set_current_folder(self.main.home)
            #self.add_filters(dialog)

        response = dialog.run()
        if response == Gtk.ResponseType.OK:
            #print("Open clicked")
        
            #print("File selected: " + dialog.get_filename())
        
            #print(dialog.get_filename())
            folder = dialog.get_filename()
            
            #folder = dialog.get_filenames()
            #print('\n\n\n',folder,'\n\n\n')
            
            self.set_folder(folder =folder)
            #print(os.path.dirname( dialog.get_filename() ))

        
        elif response == Gtk.ResponseType.CANCEL:
            print("Cancel clicked")

        dialog.destroy()
       
    def set_tooltop (self, text = ''):
        """ Function doc """
        self.btn.set_tooltip_text(text)


class FileChooser:
    """ Class doc """
    
    def __init__ (self, main_window = None , easyhybrid = False):
        """ Class initialiser """
        self.main_window = main_window
        self.easyhybrid = easyhybrid 
    
    def open (self, select_multiple = False, filters = None):

        """ Function doc """
        #main = gtkmain
        main = None#self.main_window
        filename = None
        
        chooser = Gtk.FileChooserDialog("Open File...", main,0,
                                       (Gtk.STOCK_CANCEL, Gtk.ResponseType.CANCEL,
                                        Gtk.STOCK_OPEN, Gtk.ResponseType.OK))
        #GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER
        #print (filters)
        
        if self.main_window.current_search_folder:
            chooser.set_current_folder(self.main_window.current_search_folder)
        else:
            pass
            
        
        if select_multiple:
            chooser.set_select_multiple(True)
            response = chooser.run()
            if response == Gtk.ResponseType.OK:
                filenames = chooser.get_filenames()
            chooser.destroy()
            
            # updating current_search_folder
            file_directory = os.path.dirname(filenames[0])
            self.main_window.current_search_folder = file_directory
            
            return filenames
            
            
            
        
        
        
        else:
            if filters:
                for _filter in filters:
                    chooser.add_filter(_filter)
            else:
                '''
                filter = Gtk.FileFilter()  
                filter.set_name("PKL files - *.pkl")

                filter.add_mime_type("PKL files")
                filter.add_pattern("*.pkl")
                #
                chooser.add_filter(filter)
                '''
                filter = Gtk.FileFilter()
                filter.set_name("All files")
                filter.add_pattern("*")
                #
                chooser.add_filter(filter)  
            response = chooser.run()
            if response == Gtk.ResponseType.OK:
                filename = chooser.get_filename()
                
                file_directory = os.path.dirname(filename)
                self.main_window.current_search_folder = file_directory
            
            chooser.destroy()
            return filename
